
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ARGUMENT MOVE MOVEDIR NEWROAD REFERENCEROAD START STOP TURN TURNDIR\n    expression : NEWROAD recorrido STOP expression\n               | START recorrido STOP\n    \n    recorrido : instruccion \n              | instruccion recorrido\n    \n    instruccion : MOVE MOVEDIR ARGUMENT\n                | TURN TURNDIR ARGUMENT \n                | REFERENCEROAD\n    '
    
_lr_action_items = {'NEWROAD':([0,10,],[2,2,]),'START':([0,10,],[3,3,]),'$end':([1,14,15,],[0,-2,-1,]),'MOVE':([2,3,5,8,16,17,],[6,6,6,-7,-5,-6,]),'TURN':([2,3,5,8,16,17,],[7,7,7,-7,-5,-6,]),'REFERENCEROAD':([2,3,5,8,16,17,],[8,8,8,-7,-5,-6,]),'STOP':([4,5,8,9,11,16,17,],[10,-3,-7,14,-4,-5,-6,]),'MOVEDIR':([6,],[12,]),'TURNDIR':([7,],[13,]),'ARGUMENT':([12,13,],[16,17,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,10,],[1,15,]),'recorrido':([2,3,5,],[4,9,11,]),'instruccion':([2,3,5,],[5,5,5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> NEWROAD recorrido STOP expression','expression',4,'p_expression','Interprete-Compilador - Auto - TPSySL.py',52),
  ('expression -> START recorrido STOP','expression',3,'p_expression','Interprete-Compilador - Auto - TPSySL.py',53),
  ('recorrido -> instruccion','recorrido',1,'p_recorrido','Interprete-Compilador - Auto - TPSySL.py',62),
  ('recorrido -> instruccion recorrido','recorrido',2,'p_recorrido','Interprete-Compilador - Auto - TPSySL.py',63),
  ('instruccion -> MOVE MOVEDIR ARGUMENT','instruccion',3,'p_instruccion','Interprete-Compilador - Auto - TPSySL.py',73),
  ('instruccion -> TURN TURNDIR ARGUMENT','instruccion',3,'p_instruccion','Interprete-Compilador - Auto - TPSySL.py',74),
  ('instruccion -> REFERENCEROAD','instruccion',1,'p_instruccion','Interprete-Compilador - Auto - TPSySL.py',75),
]
